title: isalog theme
description: isalog is a clean, responsive dark theme for Jekyll blogs.
show_downloads: false
google_analytics:
theme: jekyll-theme-isalog
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
