#!/bin/sh

set -e

# TypeScript type checking
npx tsc --noEmit

# Build JavaScript assets
npm run build:js

# Jekyll build and validation
bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --url-ignore '/fonts.gstatic.com/,/fonts.googleapis.com/'
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-isalog.gemspec
